bastion_ec2_instance_type = "t3.nano"
demo_ec2_instance_type    = "t3.medium"
aws_region                = "af-south-1"
demo_profile              = "aaq_demo"
project_name              = "aaq"
billing_code              = "aaq"
environment               = "demo"
