[tool.mypy]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ['litellm', "nltk", "alignscore","pgvector.sqlalchemy",
            "google.auth.transport", "google.oauth2",
            "gtts", "google.cloud", "bertopic", "hdbscan", "pydub",
            "sklearn"]
ignore_missing_imports = true

[tool.ruff]
lint.select = ["E", "F", "B", "Q", "I"]
line-length = 88
lint.ignore = ["B008"]  # Do not perform function calls in argument defaults.

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends","typer.Option"]

[tool.ruff.lint.isort]
known-first-party = ["core_backend"]

[tool.isort]
known_first_party = ["core_backend"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
markers = [
    "rails: marks tests that are testing rails. These call an LLM service."
]
asyncio_mode = "auto"

# Pytest coverage
[tool.coverage.report]
exclude_lines = [
    'if __name__ == "__main__"',
    "if __name__ == '__main__'",
    "def cli",
    "if TYPE_CHECKING:",
    "pragma: no cover",
]
omit = ["*/tests/*"]
