bastion_ec2_instance_type = "t3.nano"
ec2_instance_type         = "t4g.medium"
aws_region                = "ap-south-1"
aws_profile               = "aaq"
project_name              = "aaq"
billing_code              = "aaq"
environment               = "testing"
rds_db_instance_class     = "db.t4g.micro"
