services:
  core_backend:
    depends_on:
      - speech_service

  speech_service:
    build:
      context: ../../optional_components/speech_api
      dockerfile: Dockerfile
      args:
        PREFERRED_MODEL: "small"
    image: idinsight/speech-service:latest
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ../../optional_components/speech_api
    volumes:
      - temp:/usr/src/speech_service/temp
