authors:
  Sid:
    name: Sid
    description: Data Science Director
    avatar: https://raw.githubusercontent.com/IDinsight/ask-a-question/main/docs/blog/author-avatars/sid.png
  Carlos:
    name: Carlos
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/ask-a-question/main/docs/blog/author-avatars/carlos.jpg
  Amir:
    name: Amir
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/ask-a-question/main/docs/blog/author-avatars/amir.jpg
  Tanmay:
    name: Tanmay
    description: Product Manager
    avatar: https://raw.githubusercontent.com/IDinsight/ask-a-question/main/docs/blog/author-avatars/tanmay.png
  Suzin:
    name: Suzin
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/ask-a-question/main/docs/blog/author-avatars/suzin.png
  Mustafa:
    name: Mustafa
    description: BE Computer Engineering Student
    avatar: https://raw.githubusercontent.com/IDinsight/ask-a-question/VoiceApi/blogpost/docs/blog/author-avatars/mustafa.jpg
  Tony:
    name: Tony
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/ask-a-question/main/docs/blog/author-avatars/tony.png
  Poornima:
    name: Poornima
    description: Data Scientist
    avatar: https://raw.githubusercontent.com/IDinsight/ask-a-question/main/docs/blog/author-avatars/poornima.png
