import os

URGENCY_DETECTION_MAX_DISTANCE = os.environ.get("URGENCY_DETECTION_MAX_DISTANCE", 0.3)
URGENCY_DETECTION_MIN_PROBABILITY = os.environ.get(
    "URGENCY_DETECTION_MIN_PROBABILITY", 0.5
)
URGENCY_CLASSIFIER = os.environ.get("URGENCY_CLASSIFIER", "llm_entailment_classifier")
