"""Initial Migration

Revision ID: c5a948963236
Revises: 
Create Date: 2023-09-16 05:10:04.048830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a948963236'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-queries',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('feedback_secret_key', sa.String(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('query_metadata', sa.JSON(), nullable=False),
    sa.Column('query_datetime_utc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index(op.f('ix_user-queries_query_id'), 'user-queries', ['query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user-queries_query_id'), table_name='user-queries')
    op.drop_table('user-queries')
    # ### end Alembic commands ###
