"""Create UD Rules tables

Revision ID: 1db0d42bebbd
Revises: 45a8fa928a80
Create Date: 2024-04-26 22:28:55.874054

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1db0d42bebbd"
down_revision: Union[str, None] = "45a8fa928a80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urgency_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("urgency_rule_text", sa.String(), nullable=False),
        sa.Column(
            "urgency_rule_vector", pgvector.sqlalchemy.Vector(dim=1536), nullable=False
        ),
        sa.Column("urgency_rule_metadata", sa.JSON(), nullable=True),
        sa.Column("created_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("urgency_rules")
    # ### end Alembic commands ###
