"""add language table

Revision ID: 1ff08438751b
Revises: f269c75dbf69
Create Date: 2024-03-18 18:38:29.579259

"""

from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ff08438751b"
down_revision: Union[str, None] = "f269c75dbf69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("language_name", sa.String(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("language_id"),
    )
    op.create_index(
        "ix_languages_is_default_true",
        "languages",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default IS true"),
    )
    # add default language
    date = str(datetime.now())
    op.execute(
        f"""INSERT INTO languages
        (language_name, is_default, created_datetime_utc, updated_datetime_utc)
       VALUES ('ENGLISH', true, '{date}', '{date}')"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_languages_is_default_true",
        table_name="languages",
        postgresql_where=sa.text("is_default IS true"),
    )
    op.drop_table("languages")
    # ### end Alembic commands ###
