"""test-suzin

Revision ID: fc8af9856338
Revises: db9ff6332ffe
Create Date: 2024-08-12 15:33:09.889714

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fc8af9856338"
down_revision: Union[str, None] = "db9ff6332ffe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
