"""add contents for query table

Revision ID: 8946f1949a33
Revises: 9d0519332fdd
Create Date: 2024-07-31 11:57:57.037305

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8946f1949a33"
down_revision: Union[str, None] = "9d0519332fdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_for_query",
        sa.Column("content_for_query_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("created_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.content_id"],
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["query.query_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("content_for_query_id"),
    )
    op.create_index(
        "idx_user_id_created_datetime",
        "content_for_query",
        ["user_id", "created_datetime_utc"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_id_created_datetime", table_name="content_for_query")
    op.drop_table("content_for_query")
    # ### end Alembic commands ###
