"""add api daily quota

Revision ID: a5a6db9eca6f
Revises: 9d0519332fdd
Create Date: 2024-07-04 13:31:11.544070

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5a6db9eca6f"
down_revision: Union[str, None] = "9d0519332fdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("api_daily_quota", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "api_daily_quota")
    # ### end Alembic commands ###
