"""update_content_tags

Revision ID: 29b5ffa97758
Revises: b5ad153a53dc
Create Date: 2024-06-06 18:12:30.235465

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29b5ffa97758"
down_revision: Union[str, None] = "b5ad153a53dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("content_tags", "content-tag")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("content-tag", "content_tags")
    # ### end Alembic commands ###
