"""add recovery codes

Revision ID: 27fd893400f8
Revises: c571cf9aae63
Create Date: 2024-09-26 16:44:39.565533

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27fd893400f8"  # pragma: allowlist secret
down_revision: Union[str, None] = "6351eefb1e6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("recovery_codes", sa.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "recovery_codes")
    # ### end Alembic commands ###
