"""add content_quota to user table

Revision ID: 28861161249b
Revises: 29b5ffa97758
Create Date: 2024-06-13 12:01:07.418461

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28861161249b"
down_revision: Union[str, None] = "29b5ffa97758"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("content_quota", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "content_quota")
    # ### end Alembic commands ###
