"""Rename tts_file to tts_filepath

Revision ID: c571cf9aae63
Revises: 7192d62a0b83
Create Date: 2024-08-19 21:46:41.670438

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c571cf9aae63"  # pragma: allowlist secret
down_revision: Union[str, None] = "7192d62a0b83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query_response", sa.Column("tts_filepath", sa.String(), nullable=True)
    )
    op.drop_column("query_response", "tts_file")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query_response",
        sa.Column("tts_file", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("query_response", "tts_filepath")
    # ### end Alembic commands ###
