"""Add is_archived attribute to content table.

Revision ID: 6fd6bcd063ff
Revises: 0e0efc651e4c
Create Date: 2024-07-23 13:44:59.187906

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fd6bcd063ff"
down_revision: Union[str, None] = "0e0efc651e4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("is_archived", sa.Boolean(), nullable=True))
    op.execute("UPDATE content SET is_archived = FALSE")  # for existing rows
    op.alter_column("content", "is_archived", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "is_archived")
    # ### end Alembic commands ###
