"""add generate_tts column to query table and tts_file column to query response table

Revision ID: 7192d62a0b83
Revises: b87b336df479
Create Date: 2024-08-07 18:50:40.834060

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7192d62a0b83"  # pragma: allowlist secret
down_revision: Union[str, None] = "b87b336df479"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("query", sa.Column("generate_tts", sa.Boolean(), nullable=True))
    op.add_column("query-response", sa.Column("tts_file", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query-response", "tts_file")
    op.drop_column("query", "generate_tts")
    # ### end Alembic commands ###
