"""temp change

Revision ID: e0b52b0b5a2c
Revises: c571cf9aae63
Create Date: 2024-09-10 17:46:43.180760

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0b52b0b5a2c"
down_revision: Union[str, None] = "c571cf9aae63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("temp", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "temp")
    # ### end Alembic commands ###
