"""Add is_archived attribute to content table.

Revision ID: 0071081eb987
Revises: 4d3f01bf891f
Create Date: 2024-07-16 14:35:32.706565

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0071081eb987"
down_revision: Union[str, None] = "4d3f01bf891f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("is_archived", sa.Boolean(), nullable=True))
    op.execute("UPDATE content SET is_archived = False")  # for existing rows
    op.alter_column("content", "is_archived", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "is_archived")
    # ### end Alembic commands ###
