"""Add is_archived attribute to content table.

Revision ID: b332774c1aca
Revises: 30549f0b428a
Create Date: 2024-07-17 17:46:57.665111

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b332774c1aca"
down_revision: Union[str, None] = "30549f0b428a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("is_archived", sa.Boolean(), nullable=True))
    op.execute("UPDATE content SET is_archived = False")  # for existing rows
    op.alter_column("content", "is_archived", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "is_archived")
    # ### end Alembic commands ###
