"""add session_id to tables

including QueryDB, QueryResponseDB, QueryResponseContentDB, ResponseFeedbackDB,
and ContentFeedbackDB

Revision ID: 358588881e01
Revises: 465368ca2bac
Create Date: 2024-08-07 16:26:56.142275

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "358588881e01"
down_revision: Union[str, None] = "465368ca2bac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content_feedback", sa.Column("session_id", sa.Integer(), nullable=True)
    )
    op.add_column("query", sa.Column("session_id", sa.Integer(), nullable=True))
    op.add_column(
        "query_response", sa.Column("session_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "query_response_content", sa.Column("session_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "query_response_feedback", sa.Column("session_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query_response_feedback", "session_id")
    op.drop_column("query_response_content", "session_id")
    op.drop_column("query_response", "session_id")
    op.drop_column("query", "session_id")
    op.drop_column("content_feedback", "session_id")
    # ### end Alembic commands ###
