"""update_content_tags

Revision ID: 29b5ffa97758
Revises: b5ad153a53dc
Create Date: 2024-06-06 18:12:30.235465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29b5ffa97758"
down_revision: Union[str, None] = "b5ad153a53dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content-tag",
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.content_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.tag_id"],
        ),
        sa.PrimaryKeyConstraint("content_id", "tag_id"),
    )
    op.drop_table("content-tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content-tags",
        sa.Column("content_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"], ["content.content_id"], name="content-tags_content_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.tag_id"], name="content-tags_tag_id_fkey"
        ),
        sa.PrimaryKeyConstraint("content_id", "tag_id", name="content-tags_pkey"),
    )
    op.drop_table("content-tag")
    # ### end Alembic commands ###
