"""test-suzin

Revision ID: b188ff65ed8b
Revises: 008fa3fd5c05
Create Date: 2024-08-09 12:40:18.367164

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b188ff65ed8b"
down_revision: Union[str, None] = "008fa3fd5c05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
