"""Add is_archived attribute to content table.

Revision ID: ed80a79919fb
Revises: f562cf512c90
Create Date: 2024-07-22 14:41:15.685421

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed80a79919fb"
down_revision: Union[str, None] = "f562cf512c90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("is_archived", sa.Boolean(), nullable=True))
    op.execute("UPDATE content SET is_archived = FALSE")  # for existing rows
    op.alter_column("content", "is_archived", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "is_archived")
    # ### end Alembic commands ###
