"""Added on cascade deletion to remaining tables.

Revision ID: 75f9b6f46a31
Revises: aeb64471ae71
Create Date: 2025-02-04 17:36:38.032752

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75f9b6f46a31"  # pragma: allowlist secret
down_revision: Union[str, None] = "aeb64471ae71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_content-feedback_content_id_content", "content_feedback", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_content-feedback_query_id_query", "content_feedback", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_content_feedback_query_id_query"),
        "content_feedback",
        "query",
        ["query_id"],
        ["query_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_content_feedback_content_id_content"),
        "content_feedback",
        "content",
        ["content_id"],
        ["content_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_content_tags_content_id_content", "content_tag", type_="foreignkey"
    )
    op.drop_constraint("fk_content_tags_tag_id_tag", "content_tag", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_content_tag_tag_id_tag"),
        "content_tag",
        "tag",
        ["tag_id"],
        ["tag_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_content_tag_content_id_content"),
        "content_tag",
        "content",
        ["content_id"],
        ["content_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_query-response_query_id_query", "query_response", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_query_response_query_id_query"),
        "query_response",
        "query",
        ["query_id"],
        ["query_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_query_response_content_content_id_content",
        "query_response_content",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_query_response_content_query_id_query",
        "query_response_content",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_query_response_content_query_id_query"),
        "query_response_content",
        "query",
        ["query_id"],
        ["query_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_query_response_content_content_id_content"),
        "query_response_content",
        "content",
        ["content_id"],
        ["content_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_query-response-feedback_query_id_query",
        "query_response_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_query_response_feedback_query_id_query"),
        "query_response_feedback",
        "query",
        ["query_id"],
        ["query_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_urgency-response_query_id_urgency-query",
        "urgency_response",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_urgency_response_query_id_urgency_query"),
        "urgency_response",
        "urgency_query",
        ["query_id"],
        ["urgency_query_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_urgency_response_query_id_urgency_query"),
        "urgency_response",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_urgency-response_query_id_urgency-query",
        "urgency_response",
        "urgency_query",
        ["query_id"],
        ["urgency_query_id"],
    )
    op.drop_constraint(
        op.f("fk_query_response_feedback_query_id_query"),
        "query_response_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_query-response-feedback_query_id_query",
        "query_response_feedback",
        "query",
        ["query_id"],
        ["query_id"],
    )
    op.drop_constraint(
        op.f("fk_query_response_content_content_id_content"),
        "query_response_content",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_query_response_content_query_id_query"),
        "query_response_content",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_query_response_content_query_id_query",
        "query_response_content",
        "query",
        ["query_id"],
        ["query_id"],
    )
    op.create_foreign_key(
        "fk_query_response_content_content_id_content",
        "query_response_content",
        "content",
        ["content_id"],
        ["content_id"],
    )
    op.drop_constraint(
        op.f("fk_query_response_query_id_query"), "query_response", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_query-response_query_id_query",
        "query_response",
        "query",
        ["query_id"],
        ["query_id"],
    )
    op.drop_constraint(
        op.f("fk_content_tag_content_id_content"), "content_tag", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_content_tag_tag_id_tag"), "content_tag", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_content_tags_tag_id_tag", "content_tag", "tag", ["tag_id"], ["tag_id"]
    )
    op.create_foreign_key(
        "fk_content_tags_content_id_content",
        "content_tag",
        "content",
        ["content_id"],
        ["content_id"],
    )
    op.drop_constraint(
        op.f("fk_content_feedback_content_id_content"),
        "content_feedback",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_content_feedback_query_id_query"),
        "content_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_content-feedback_query_id_query",
        "content_feedback",
        "query",
        ["query_id"],
        ["query_id"],
    )
    op.create_foreign_key(
        "fk_content-feedback_content_id_content",
        "content_feedback",
        "content",
        ["content_id"],
        ["content_id"],
    )
    # ### end Alembic commands ###
