"""add display number

Revision ID: b1daed9f42c4
Revises: 79c762e9b073
Create Date: 2025-03-12 16:55:56.360931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1daed9f42c4"  # pragma: allowlist secret
down_revision: Union[str, None] = "79c762e9b073"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("display_number", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "display_number")
    # ### end Alembic commands ###
