"""Added doc_language to workspace DB.

Revision ID: 3c54b4f5decf
Revises: 93877529eb0f
Create Date: 2025-10-07 09:23:12.056210

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c54b4f5decf"
down_revision: Union[str, None] = "93877529eb0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("doc_language", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "doc_language")
    # ### end Alembic commands ###
