"""add display number

Revision ID: b1daed9f42c4
Revises: 79c762e9b073
Create Date: 2025-03-12 16:55:56.360931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1daed9f42c4"  # pragma: allowlist secret
down_revision: Union[str, None] = "79c762e9b073"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content",
        sa.Column("display_number", sa.Integer(), nullable=False, server_default="0"),
    )

    connection = op.get_bind()

    # 2
    workspaces = connection.execute(sa.text('SELECT * FROM "workspace"')).mappings()
    for workspace in workspaces:
        workspace_id = workspace["workspace_id"]
        content = connection.execute(
            sa.text(
                f'SELECT * FROM "content" WHERE "workspace_id" = {workspace_id} '
                f'ORDER BY "created_datetime_utc"'
            )
        ).mappings()
        for i, row in enumerate(content):
            connection.execute(
                sa.text(
                    f'UPDATE "content" SET "display_number" = {i + 1} '
                    f'WHERE "content_id" = {row["content_id"]}'
                )
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "display_number")
    # ### end Alembic commands ###
