"""add is_active and is_validated columns

Revision ID: 6696ae641e6e
Revises: 8197de622b04
Create Date: 2025-04-15 10:36:36.259646

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6696ae641e6e"
down_revision: Union[str, None] = "8197de622b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content",
        sa.Column(
            "is_validated", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    op.add_column(
        "content",
        sa.Column(
            "is_active",
            sa.Boolean(),
            sa.Computed(
                "CASE WHEN (is_archived = true) THEN false "
                "WHEN (is_validated = false) THEN false ELSE true END",
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "is_active")
    op.drop_column("content", "is_validated")
    # ### end Alembic commands ###
