"""Updated all databases to use workspace_id instead of user_id for workspaces.
Applied naming conventions.

Revision ID: 8a14f17bde33
Revises: 27fd893400f8
Create Date: 2025-01-29 12:12:07.724095

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8a14f17bde33"  # pragma: allowlist secret
down_revision: Union[str, None] = "27fd893400f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace",
        sa.Column("api_daily_quota", sa.Integer(), nullable=True),
        sa.Column("api_key_first_characters", sa.String(length=5), nullable=True),
        sa.Column(
            "api_key_updated_datetime_utc", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("content_quota", sa.Integer(), nullable=True),
        sa.Column("created_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hashed_api_key", sa.String(length=96), nullable=True),
        sa.Column("updated_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("workspace_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_workspace")),
        sa.UniqueConstraint("hashed_api_key", name=op.f("uq_workspace_hashed_api_key")),
        sa.UniqueConstraint("workspace_name", name=op.f("uq_workspace_workspace_name")),
    )
    op.create_table(
        "user_workspace",
        sa.Column("created_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "default_workspace",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("updated_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "user_role",
            sa.Enum("ADMIN", "READ_ONLY", name="userroles", native_enum=False),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.user_id"], name=op.f("fk_user_workspace_user_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.workspace_id"],
            name=op.f("fk_user_workspace_workspace_id_workspace"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "workspace_id", name=op.f("pk_user_workspace")
        ),
    )
    op.add_column("content", sa.Column("workspace_id", sa.Integer(), nullable=False))
    op.drop_constraint("fk_content_user", "content", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_content_workspace_id_workspace"),
        "content",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("content", "user_id")
    op.add_column(
        "content_feedback", sa.Column("workspace_id", sa.Integer(), nullable=False)
    )
    op.drop_index("ix_content-feedback_feedback_id", table_name="content_feedback")
    op.create_index(
        op.f("ix_content_feedback_feedback_id"),
        "content_feedback",
        ["feedback_id"],
        unique=False,
    )
    op.drop_constraint(
        "fk_content_feedback_user_id_user", "content_feedback", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_content_feedback_workspace_id_workspace"),
        "content_feedback",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("content_feedback", "user_id")
    op.add_column("query", sa.Column("workspace_id", sa.Integer(), nullable=False))
    op.drop_constraint("fk_query_user", "query", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_query_workspace_id_workspace"),
        "query",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("query", "user_id")
    op.add_column(
        "query_response", sa.Column("workspace_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "fk_query_response_user_id_user", "query_response", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_query_response_workspace_id_workspace"),
        "query_response",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("query_response", "user_id")
    op.add_column(
        "query_response_content",
        sa.Column("workspace_id", sa.Integer(), nullable=False),
    )
    op.drop_index("idx_user_id_created_datetime", table_name="query_response_content")
    op.create_index(
        "idx_workspace_id_created_datetime",
        "query_response_content",
        ["workspace_id", "created_datetime_utc"],
        unique=False,
    )
    op.drop_constraint(
        "fk_query_response_content_user_id_user",
        "query_response_content",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_query_response_content_workspace_id_workspace"),
        "query_response_content",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("query_response_content", "user_id")
    op.add_column(
        "query_response_feedback",
        sa.Column("workspace_id", sa.Integer(), nullable=False),
    )
    op.drop_index(
        "ix_query-response-feedback_feedback_id", table_name="query_response_feedback"
    )
    op.create_index(
        op.f("ix_query_response_feedback_feedback_id"),
        "query_response_feedback",
        ["feedback_id"],
        unique=False,
    )
    op.drop_constraint(
        "fk_query_response_feedback_user_id_user",
        "query_response_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_query_response_feedback_workspace_id_workspace"),
        "query_response_feedback",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("query_response_feedback", "user_id")
    op.add_column("tag", sa.Column("workspace_id", sa.Integer(), nullable=False))
    op.drop_constraint("fk_tag_user_id_user", "tag", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_tag_workspace_id_workspace"),
        "tag",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("tag", "user_id")
    op.add_column(
        "urgency_query", sa.Column("workspace_id", sa.Integer(), nullable=False)
    )
    op.drop_index("ix_urgency-query_urgency_query_id", table_name="urgency_query")
    op.create_index(
        op.f("ix_urgency_query_urgency_query_id"),
        "urgency_query",
        ["urgency_query_id"],
        unique=False,
    )
    op.drop_constraint("fk_urgency_query_user", "urgency_query", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_urgency_query_workspace_id_workspace"),
        "urgency_query",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("urgency_query", "user_id")
    op.add_column(
        "urgency_response", sa.Column("workspace_id", sa.Integer(), nullable=False)
    )
    op.drop_index(
        "ix_urgency-response_urgency_response_id", table_name="urgency_response"
    )
    op.create_index(
        op.f("ix_urgency_response_urgency_response_id"),
        "urgency_response",
        ["urgency_response_id"],
        unique=False,
    )
    op.drop_constraint(
        "fk_urgency_response_user_id_user", "urgency_response", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_urgency_response_workspace_id_workspace"),
        "urgency_response",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("urgency_response", "user_id")
    op.add_column(
        "urgency_rule", sa.Column("workspace_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("fk_urgency_rule_user", "urgency_rule", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_urgency_rule_workspace_id_workspace"),
        "urgency_rule",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_column("urgency_rule", "user_id")
    op.drop_constraint("uq_user_hashed_api_key", "user", type_="unique")
    op.drop_column("user", "content_quota")
    op.drop_column("user", "api_daily_quota")
    op.drop_column("user", "hashed_api_key")
    op.drop_column("user", "api_key_first_characters")
    op.drop_column("user", "is_admin")
    op.drop_column("user", "api_key_updated_datetime_utc")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "api_key_updated_datetime_utc",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "is_admin",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "api_key_first_characters",
            sa.VARCHAR(length=5),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "hashed_api_key", sa.VARCHAR(length=96), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column("api_daily_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("content_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint("uq_user_hashed_api_key", "user", ["hashed_api_key"])
    op.add_column(
        "urgency_rule",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_urgency_rule_workspace_id_workspace"),
        "urgency_rule",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_urgency_rule_user", "urgency_rule", "user", ["user_id"], ["user_id"]
    )
    op.drop_column("urgency_rule", "workspace_id")
    op.add_column(
        "urgency_response",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_urgency_response_workspace_id_workspace"),
        "urgency_response",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_urgency_response_user_id_user",
        "urgency_response",
        "user",
        ["user_id"],
        ["user_id"],
    )
    op.drop_index(
        op.f("ix_urgency_response_urgency_response_id"), table_name="urgency_response"
    )
    op.create_index(
        "ix_urgency-response_urgency_response_id",
        "urgency_response",
        ["urgency_response_id"],
        unique=False,
    )
    op.drop_column("urgency_response", "workspace_id")
    op.add_column(
        "urgency_query",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_urgency_query_workspace_id_workspace"),
        "urgency_query",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_urgency_query_user", "urgency_query", "user", ["user_id"], ["user_id"]
    )
    op.drop_index(op.f("ix_urgency_query_urgency_query_id"), table_name="urgency_query")
    op.create_index(
        "ix_urgency-query_urgency_query_id",
        "urgency_query",
        ["urgency_query_id"],
        unique=False,
    )
    op.drop_column("urgency_query", "workspace_id")
    op.add_column(
        "tag", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(op.f("fk_tag_workspace_id_workspace"), "tag", type_="foreignkey")
    op.create_foreign_key(
        "fk_tag_user_id_user", "tag", "user", ["user_id"], ["user_id"]
    )
    op.drop_column("tag", "workspace_id")
    op.add_column(
        "query_response_feedback",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_query_response_feedback_workspace_id_workspace"),
        "query_response_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_query_response_feedback_user_id_user",
        "query_response_feedback",
        "user",
        ["user_id"],
        ["user_id"],
    )
    op.drop_index(
        op.f("ix_query_response_feedback_feedback_id"),
        table_name="query_response_feedback",
    )
    op.create_index(
        "ix_query-response-feedback_feedback_id",
        "query_response_feedback",
        ["feedback_id"],
        unique=False,
    )
    op.drop_column("query_response_feedback", "workspace_id")
    op.add_column(
        "query_response_content",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_query_response_content_workspace_id_workspace"),
        "query_response_content",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_query_response_content_user_id_user",
        "query_response_content",
        "user",
        ["user_id"],
        ["user_id"],
    )
    op.drop_index(
        "idx_workspace_id_created_datetime", table_name="query_response_content"
    )
    op.create_index(
        "idx_user_id_created_datetime",
        "query_response_content",
        ["user_id", "created_datetime_utc"],
        unique=False,
    )
    op.drop_column("query_response_content", "workspace_id")
    op.add_column(
        "query_response",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_query_response_workspace_id_workspace"),
        "query_response",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_query_response_user_id_user",
        "query_response",
        "user",
        ["user_id"],
        ["user_id"],
    )
    op.drop_column("query_response", "workspace_id")
    op.add_column(
        "query", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(
        op.f("fk_query_workspace_id_workspace"), "query", type_="foreignkey"
    )
    op.create_foreign_key("fk_query_user", "query", "user", ["user_id"], ["user_id"])
    op.drop_column("query", "workspace_id")
    op.add_column(
        "content_feedback",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_content_feedback_workspace_id_workspace"),
        "content_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_content_feedback_user_id_user",
        "content_feedback",
        "user",
        ["user_id"],
        ["user_id"],
    )
    op.drop_index(
        op.f("ix_content_feedback_feedback_id"), table_name="content_feedback"
    )
    op.create_index(
        "ix_content-feedback_feedback_id",
        "content_feedback",
        ["feedback_id"],
        unique=False,
    )
    op.drop_column("content_feedback", "workspace_id")
    op.add_column(
        "content",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_content_workspace_id_workspace"), "content", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_content_user", "content", "user", ["user_id"], ["user_id"]
    )
    op.drop_column("content", "workspace_id")
    op.drop_table("user_workspace")
    op.drop_table("workspace")
    # ### end Alembic commands ###
