"""add page limits to workspace

Revision ID: d4f7e14f5e9e
Revises: 6696ae641e6e
Create Date: 2025-04-21 09:30:24.565836

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4f7e14f5e9e"
down_revision: Union[str, None] = "6696ae641e6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspace", sa.Column("page_quota", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "page_quota")
    # ### end Alembic commands ###
