"""Added on cascade deletion for user, workspace, and user workspace tables. Also
updated all other relevant tables that uses workspace.workspace_id for on cascade
deletion.

Revision ID: aeb64471ae71
Revises: 8a14f17bde33
Create Date: 2025-01-30 08:53:03.168819

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aeb64471ae71"
down_revision: Union[str, None] = "8a14f17bde33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_content_workspace_id_workspace", "content", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_content_workspace_id_workspace"),
        "content",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_content_feedback_workspace_id_workspace",
        "content_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_content_feedback_workspace_id_workspace"),
        "content_feedback",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_query_workspace_id_workspace", "query", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_query_workspace_id_workspace"),
        "query",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_query_response_workspace_id_workspace", "query_response", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_query_response_workspace_id_workspace"),
        "query_response",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_query_response_content_workspace_id_workspace",
        "query_response_content",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_query_response_content_workspace_id_workspace"),
        "query_response_content",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_query_response_feedback_workspace_id_workspace",
        "query_response_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_query_response_feedback_workspace_id_workspace"),
        "query_response_feedback",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_tag_workspace_id_workspace", "tag", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_tag_workspace_id_workspace"),
        "tag",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_urgency_query_workspace_id_workspace", "urgency_query", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_urgency_query_workspace_id_workspace"),
        "urgency_query",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_urgency_response_workspace_id_workspace",
        "urgency_response",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_urgency_response_workspace_id_workspace"),
        "urgency_response",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_urgency_rule_workspace_id_workspace", "urgency_rule", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_urgency_rule_workspace_id_workspace"),
        "urgency_rule",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_user_workspace_workspace_id_workspace", "user_workspace", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_user_workspace_user_id_user", "user_workspace", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_user_workspace_user_id_user"),
        "user_workspace",
        "user",
        ["user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_user_workspace_workspace_id_workspace"),
        "user_workspace",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_workspace_workspace_id_workspace"),
        "user_workspace",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_workspace_user_id_user"), "user_workspace", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_user_workspace_user_id_user",
        "user_workspace",
        "user",
        ["user_id"],
        ["user_id"],
    )
    op.create_foreign_key(
        "fk_user_workspace_workspace_id_workspace",
        "user_workspace",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(
        op.f("fk_urgency_rule_workspace_id_workspace"),
        "urgency_rule",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_urgency_rule_workspace_id_workspace",
        "urgency_rule",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(
        op.f("fk_urgency_response_workspace_id_workspace"),
        "urgency_response",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_urgency_response_workspace_id_workspace",
        "urgency_response",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(
        op.f("fk_urgency_query_workspace_id_workspace"),
        "urgency_query",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_urgency_query_workspace_id_workspace",
        "urgency_query",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(op.f("fk_tag_workspace_id_workspace"), "tag", type_="foreignkey")
    op.create_foreign_key(
        "fk_tag_workspace_id_workspace",
        "tag",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(
        op.f("fk_query_response_feedback_workspace_id_workspace"),
        "query_response_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_query_response_feedback_workspace_id_workspace",
        "query_response_feedback",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(
        op.f("fk_query_response_content_workspace_id_workspace"),
        "query_response_content",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_query_response_content_workspace_id_workspace",
        "query_response_content",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(
        op.f("fk_query_response_workspace_id_workspace"),
        "query_response",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_query_response_workspace_id_workspace",
        "query_response",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(
        op.f("fk_query_workspace_id_workspace"), "query", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_query_workspace_id_workspace",
        "query",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(
        op.f("fk_content_feedback_workspace_id_workspace"),
        "content_feedback",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_content_feedback_workspace_id_workspace",
        "content_feedback",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    op.drop_constraint(
        op.f("fk_content_workspace_id_workspace"), "content", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_content_workspace_id_workspace",
        "content",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    # ### end Alembic commands ###
