"""Error table - map to query table 2

Revision ID: 2c8e6e7b24b7
Revises: d1eb21fec9f9
Create Date: 2024-01-19 14:45:13.758189

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2c8e6e7b24b7"
down_revision: Union[str, None] = "d1eb21fec9f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
