"""Added user_id to ContentDB

Revision ID: 3cdc029625e5
Revises: e8ddc3de6210
Create Date: 2024-04-25 21:46:56.540434

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cdc029625e5"
down_revision: Union[str, None] = "e8ddc3de6210"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("user_id", sa.String(), nullable=False))
    op.drop_index(
        "content_idx",
        table_name="content",
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "content_idx",
        "content",
        ["content_embedding"],
        unique=False,
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_column("content", "user_id")
    # ### end Alembic commands ###
