"""create feedback table

Revision ID: 42fe00da1c48
Revises: c5a948963236
Create Date: 2023-09-18 06:07:06.316009

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42fe00da1c48"
down_revision: Union[str, None] = "c5a948963236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("feedback_id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("feedback_text", sa.String(), nullable=False),
        sa.Column("feedback_datetime_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["query.query_id"],
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    op.create_index(
        op.f("ix_feedback_feedback_id"), "feedback", ["feedback_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_feedback_id"), table_name="feedback")
    op.drop_table("feedback")
    # ### end Alembic commands ###
