"""add user_id to UD tables

Revision ID: 4a3f264ab221
Revises: 5b7568c848c4
Create Date: 2024-05-03 10:41:07.056888

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a3f264ab221"
down_revision: Union[str, None] = "75235585abd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("urgency-query", sa.Column("user_id", sa.String(), nullable=False))
    op.create_foreign_key(None, "urgency-query", "user", ["user_id"], ["user_id"])
    op.add_column("urgency-rule", sa.Column("user_id", sa.String(), nullable=False))
    op.create_foreign_key(None, "urgency-rule", "user", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "urgency-rule", type_="foreignkey")
    op.drop_column("urgency-rule", "user_id")
    op.drop_constraint(None, "urgency-query", type_="foreignkey")
    op.drop_column("urgency-query", "user_id")
    # ### end Alembic commands ###
