"""content response table

Revision ID: 4ceb0e08bac7
Revises: 50caccd9e332
Create Date: 2024-04-19 11:53:07.383033

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ceb0e08bac7"
down_revision: Union[str, None] = "50caccd9e332"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_feedback",
        sa.Column("feedback_id", sa.Integer(), nullable=False),
        sa.Column("feedback_sentiment", sa.String(), nullable=True),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("feedback_text", sa.String(), nullable=True),
        sa.Column("feedback_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.content_id"],
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["user-queries.query_id"],
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    op.create_index(
        op.f("ix_content_feedback_feedback_id"),
        "content_feedback",
        ["feedback_id"],
        unique=False,
    )
    op.create_table(
        "response_feedback",
        sa.Column("feedback_id", sa.Integer(), nullable=False),
        sa.Column("feedback_sentiment", sa.String(), nullable=True),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("feedback_text", sa.String(), nullable=True),
        sa.Column("feedback_datetime_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["user-queries.query_id"],
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    op.create_index(
        op.f("ix_response_feedback_feedback_id"),
        "response_feedback",
        ["feedback_id"],
        unique=False,
    )
    op.drop_index("ix_feedback_feedback_id", table_name="feedback")
    op.drop_table("feedback")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("feedback_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("query_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("feedback_text", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "feedback_datetime_utc",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "feedback_sentiment", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["query_id"], ["user-queries.query_id"], name="feedback_query_id_fkey"
        ),
        sa.PrimaryKeyConstraint("feedback_id", name="feedback_pkey"),
    )
    op.create_index(
        "ix_feedback_feedback_id", "feedback", ["feedback_id"], unique=False
    )
    op.drop_index(
        op.f("ix_response_feedback_feedback_id"), table_name="response_feedback"
    )
    op.drop_table("response_feedback")
    op.drop_index(
        op.f("ix_content_feedback_feedback_id"), table_name="content_feedback"
    )
    op.drop_table("content_feedback")
    # ### end Alembic commands ###
