"""Create WhatsApp Tables

Revision ID: 56b62dbe2d89
Revises: 8929d5c246e7
Create Date: 2023-11-07 18:26:51.842395

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56b62dbe2d89"
down_revision: Union[str, None] = "8929d5c246e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatsapp_incoming_messages",
        sa.Column("incoming_id", sa.Integer(), nullable=False),
        sa.Column("msg_id_from_whatsapp", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("phonenumber_id", sa.String(), nullable=False),
        sa.Column("incoming_datetime_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("incoming_id"),
    )
    op.create_table(
        "whatsapp_responses",
        sa.Column("response_id", sa.Integer(), nullable=False),
        sa.Column("incoming_id", sa.Integer(), nullable=False),
        sa.Column("response", sa.String(), nullable=True),
        sa.Column("response_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incoming_id"],
            ["whatsapp_incoming_messages.incoming_id"],
        ),
        sa.PrimaryKeyConstraint("response_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("whatsapp_responses")
    op.drop_table("whatsapp_incoming_messages")
    # ### end Alembic commands ###
