"""Create UD tables

Revision ID: 5b4b580d4f1c
Revises: e8ddc3de6210
Create Date: 2024-04-27 22:21:48.394836

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b4b580d4f1c"
down_revision: Union[str, None] = "e8ddc3de6210"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urgency_queries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_text", sa.String(), nullable=False),
        sa.Column("message_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("feedback_secret_key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_urgency_queries_id"), "urgency_queries", ["id"], unique=False
    )
    op.create_table(
        "urgency_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("urgency_rule_text", sa.String(), nullable=False),
        sa.Column(
            "urgency_rule_vector", pgvector.sqlalchemy.Vector(dim=1536), nullable=False
        ),
        sa.Column("urgency_rule_metadata", sa.JSON(), nullable=True),
        sa.Column("created_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "urgency_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_urgent", sa.Boolean(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("response_datetime_utc", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["urgency_queries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_urgency_responses_id"), "urgency_responses", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urgency_responses_id"), table_name="urgency_responses")
    op.drop_table("urgency_responses")
    op.drop_table("urgency_rules")
    op.drop_index(op.f("ix_urgency_queries_id"), table_name="urgency_queries")
    op.drop_table("urgency_queries")
    # ### end Alembic commands ###
