"""unique_language_content_combination

Revision ID: 6187d34e3bf2
Revises: 99d716c4ed52
Create Date: 2024-04-09 11:32:41.546616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6187d34e3bf2"
down_revision: Union[str, None] = "99d716c4ed52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_content_id_language_id", "content_texts", ["content_id", "language_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_content_id_language_id", "content_texts", type_="unique")
    # ### end Alembic commands ###
