"""add content_text

Revision ID: 63e31be75478
Revises: 1ff08438751b
Create Date: 2024-03-20 15:51:28.678881

"""

from typing import Sequence, Union

from alembic import op
from app.contents.config import (
    PGVECTOR_DISTANCE,
    PGVECTOR_EF_CONSTRUCTION,
    PGVECTOR_M,
)
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "63e31be75478"
down_revision: Union[str, None] = "1ff08438751b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contents",
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("content_id"),
    )
    op.create_table(
        "content_texts",
        sa.Column("content_text_id", sa.Integer(), nullable=False),
        sa.Column(
            "content_embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=False
        ),
        sa.Column("content_title", sa.String(length=150), nullable=False),
        sa.Column("content_text", sa.String(length=2000), nullable=False),
        sa.Column("created_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("content_metadata", sa.JSON(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.content_id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.language_id"],
        ),
        sa.PrimaryKeyConstraint("content_text_id"),
    )
    op.drop_index(
        "content_idx",
        table_name="concontent_textstent",
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_table("content")
    op.execute(
        f"""CREATE INDEX content_idx ON content_texts
        USING hnsw (content_embedding {PGVECTOR_DISTANCE})
        WITH (m = {PGVECTOR_M}, ef_construction = {PGVECTOR_EF_CONSTRUCTION})"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "content_idx",
        table_name="content_texts",
        postgresql_using="hnsw",
        postgresql_with={
            "M": {PGVECTOR_M},
            "ef_construction": {PGVECTOR_EF_CONSTRUCTION},
        },
        postgresql_ops={"embedding": {PGVECTOR_DISTANCE}},
    )
    op.create_table(
        "content",
        sa.Column("content_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "content_embedding",
            pgvector.sqlalchemy.Vector(dim=1536),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "content_title", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
        sa.Column(
            "content_text", sa.VARCHAR(length=2000), autoincrement=False, nullable=False
        ),
        sa.Column(
            "content_language", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "content_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_datetime_utc",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_datetime_utc",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("content_id", name="content_pkey"),
    )
    op.create_index(
        "content_idx",
        "content",
        ["content_embedding"],
        unique=False,
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_table("content_texts")
    op.drop_table("contents")
    # ### end Alembic commands ###
