"""Content tables added

Revision ID: 6f1daa64a188
Revises: 7499a97bc5f3
Create Date: 2023-09-19 01:59:23.011018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f1daa64a188"
down_revision: Union[str, None] = "7499a97bc5f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("content_text", sa.String(), nullable=False),
        sa.Column("content_metadata", sa.JSON(), nullable=False),
        sa.Column("created_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("content_id"),
    )
    op.create_index(
        op.f("ix_content_content_id"), "content", ["content_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_content_content_id"), table_name="content")
    op.drop_table("content")
    # ### end Alembic commands ###
