"""add user_id column to query table

Revision ID: 72f5b77b54f3
Revises: e2fece37020f
Create Date: 2024-04-27 16:00:54.813516

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72f5b77b54f3"
down_revision: Union[str, None] = "e2fece37020f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("query", sa.Column("user_id", sa.String(), nullable=False))
    op.create_foreign_key(None, "query", "user", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "query", type_="foreignkey")
    op.drop_column("query", "user_id")
    # ### end Alembic commands ###
