"""Content tables added

Revision ID: 7499a97bc5f3
Revises: 42fe00da1c48
Create Date: 2023-09-19 01:52:35.164890

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7499a97bc5f3"
down_revision: Union[str, None] = "42fe00da1c48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
