"""make username and key columns unique

Revision ID: 75235585abd7
Revises: 5b7568c848c4
Create Date: 2024-05-06 15:58:04.359309

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75235585abd7"
down_revision: Union[str, None] = "5b7568c848c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "content_idx",
        table_name="content",
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_unique_constraint(None, "user", ["username"])
    op.create_unique_constraint(None, "user", ["hashed_retrieval_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.create_index(
        "content_idx",
        "content",
        ["content_embedding"],
        unique=False,
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###
