"""added vote counters to content

Revision ID: 7528bd58da02
Revises: 4ceb0e08bac7
Create Date: 2024-04-19 12:19:11.277418

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7528bd58da02"
down_revision: Union[str, None] = "4ceb0e08bac7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("positive_votes", sa.Integer(), nullable=False))
    op.add_column("content", sa.Column("negative_votes", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "negative_votes")
    op.drop_column("content", "positive_votes")
    # ### end Alembic commands ###
