"""Create error table

Revision ID: 9eaf63e424ea
Revises: 56b62dbe2d89
Create Date: 2024-01-22 21:45:29.559047

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9eaf63e424ea"
down_revision: Union[str, None] = "56b62dbe2d89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user-query-response-errors",
        sa.Column("error_id", sa.Integer(), nullable=False),
        sa.Column("query_id", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=False),
        sa.Column("error_type", sa.String(), nullable=False),
        sa.Column("error_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("debug_info", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["user-queries.query_id"],
        ),
        sa.PrimaryKeyConstraint("error_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user-query-response-errors")
    # ### end Alembic commands ###
