"""Add content table

Revision ID: a5b29bc66bb5
Revises: 9eaf63e424ea
Create Date: 2024-02-15 17:45:26.803356

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5b29bc66bb5"
down_revision: Union[str, None] = "9eaf63e424ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table(
        "content",
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column(
            "content_embedding", pgvector.sqlalchemy.Vector(dim=1536.0), nullable=False
        ),
        sa.Column("content_title", sa.String(), nullable=False),
        sa.Column("content_text", sa.String(), nullable=False),
        sa.Column(
            "content_language",
            sa.Enum(
                "ENGLISH",
                "XHOSA",
                "ZULU",
                "AFRIKAANS",
                "HINDI",
                "UNKNOWN",
                name="identifiedlanguage",
            ),
            nullable=False,
        ),
        sa.Column("content_metadata", sa.JSON(), nullable=False),
        sa.Column("created_datetime_utc", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("content_id"),
    )
    op.execute(
        "CREATE INDEX content_idx ON content"
        " USING hnsw (content_embedding vector_l2_ops)"
        "WITH (m = 16, ef_construction = 64)"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "content_idx",
        table_name="content",
        postgresql_using="hnsw",
        postgresql_with={"M": "16", "ef_construction": "64"},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.drop_table("content")
    op.execute("DROP TYPE IF EXISTS identifiedlanguage;")
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
