"""Error table - map to query table

Revision ID: d1eb21fec9f9
Revises: 32a59499d174
Create Date: 2024-01-19 14:42:43.069462

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d1eb21fec9f9"
down_revision: Union[str, None] = "32a59499d174"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
