"""change user_id column in content table to ForeignKey

Revision ID: d4675b392e9c
Revises: 0d17ec72fe65
Create Date: 2024-04-26 18:55:04.107711

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4675b392e9c"
down_revision: Union[str, None] = "0d17ec72fe65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "content", "user", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "content", type_="foreignkey")
    # ### end Alembic commands ###
