"""rename column responses to content_response

Revision ID: e4ee9998e82f
Revises: 8929d5c246e7
Create Date: 2023-10-27 10:30:47.167821

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4ee9998e82f"
down_revision: Union[str, None] = "8929d5c246e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user-query-responses", sa.Column("content_response", sa.JSON(), nullable=False)
    )
    op.drop_column("user-query-responses", "responses")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user-query-responses",
        sa.Column(
            "responses",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user-query-responses", "content_response")
    # ### end Alembic commands ###
