"""remove unused /contents table

Revision ID: ee679897eeb5
Revises: cda1098017b5
Create Date: 2023-10-12 10:50:32.035372

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee679897eeb5"
down_revision: Union[str, None] = "cda1098017b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_content_content_id", table_name="content")
    op.drop_table("content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("content_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content_text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "content_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_datetime_utc",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_datetime_utc",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("content_id", name="content_pkey"),
    )
    op.create_index("ix_content_content_id", "content", ["content_id"], unique=False)
    # ### end Alembic commands ###
