gcp_location          = "asia-south1"
gcp_zone              = "asia-south1-b"
deployment_group_name = "aaq"
environment           = "production"
gce_instance_type     = "n1-standard-4"
db_tier               = "db-custom-4-16384"
admin_username        = "admin"
