name: Alembic Migration Check

env:
  BRANCH_NAME: tonyzhao6-gha-workflow-for-alembic-migration

on:
  pull_request:
    branches:
      - ${{ env.BRANCH_NAME }}
    paths:
      - "core_backend/migrations/versions/**.py"
      - ".github/workflows/alembic-migrations.yaml"

  push:
    branches:
      - ${{ env.BRANCH_NAME }}
    paths:
      - "core_backend/migrations/versions/**.py"
      - ".github/workflows/alembic-migrations.yaml"

jobs:
  check-for-outdated-heads:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout BRANCH_NAME branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python libraries
        run: |
          python -m pip install -r core_backend/requirements.txt

      - name: Get Alembic head of BRANCH_NAME branch
        run: |
          cd core_backend
          alembic_head_main=$(alembic heads | awk '{print $1}')
          echo "ALEMBIC_HEAD_MAIN=${alembic_head_main}" >> $GITHUB_ENV

      - name: Checkout PR branch
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check if Alembic head revision from BRANCH_NAME branch exists in feature branch DURING PR
        if: github.event_name == 'pull_request'
        run: |
          cd core_backend
          alembic_history_pr=$(alembic history)
          if echo "${alembic_history_pr}" | grep -q "$ALEMBIC_HEAD_MAIN"; then
              echo "Alembic head revision from ${{ env.BRANCH_NAME }} branch exists in PR branch."
          else
              echo "Alembic head revision from ${{ env.BRANCH_NAME }} branch does NOT exist in PR branch. Update your migrations to align with ${{ env.BRANCH_NAME }} branch."
              exit 1
          fi

      - name: Check for multiple Alembic heads after PR is merged
        if: github.event_name == 'push'
        run: |
          cd core_backend
          alembic_heads=$(alembic heads | wc -l)
          if [ "$alembic_heads" -gt 1 ]; then
              echo "Multiple Alembic heads detected in the ${{ env.BRANCH_NAME }} branch after PR merge. Resolve the heads to maintain a single migration history."
              exit 1
          else
              echo "No multiple Alembic heads detected."
