name: Speech Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "optional_components/speech_api/**"
      - ".github/workflows/test_speech_api.yaml"

env:
  PREFERRED_MODEL: base
  WHISPER_MODEL_DIR: whisper_models
  PIPER_MODELS_DIR: models/piper
  ENG_MODEL_NAME: en_US-arctic-medium.onnx
  SWAHILI_MODEL_NAME: sw_CD-lanfrica-medium.onnx

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Speech Unit Tests
        env:
          PREFERRED_MODEL: ${{ env.PREFERRED_MODEL }}
          WHISPER_MODEL_DIR: ${{ env.WHISPER_MODEL_DIR }}
          PIPER_MODELS_DIR: ${{ env.PIPER_MODELS_DIR }}
          ENG_MODEL_NAME: ${{ env.ENG_MODEL_NAME }}
          SWAHILI_MODEL_NAME: ${{ env.SWAHILI_MODEL_NAME }}
        run: |
          cd optional_components/speech_api
          make tests
