name: Speech Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "optional_components/speech_api/**"

env:
  PREFERRED_MODEL: base
  WHISPER_MODEL_DIR: whisper_models

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r optional_components/speech_api/requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
          python -m pip install -r requirements-dev.txt
          python -m pip install pytest

      - name: Run Speech Unit Tests
        env:
          PREFERRED_MODEL: ${{ env.PREFERRED_MODEL }}
          WHISPER_MODEL_DIR: ${{ env.WHISPER_MODEL_DIR }}
        run: |
          mkdir -p $WHISPER_MODEL_DIR
          cd optional_components/speech_api
          python -m pytest
          cd ../..
          rm -rf $WHISPER_MODEL_DIR
